// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package odm.proxies;

public enum OrderStatus
{
	NewOrder(new String[][] { new String[] { "en_US", "NewOrder" }, new String[] { "nl_NL", "Nieuwe order" } }),
	Invoiced(new String[][] { new String[] { "en_US", "Invoiced" }, new String[] { "nl_NL", "Gefactureerd" } });

	private java.util.Map<String,String> captions;

	private OrderStatus(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
