// This file was generated by Mendix Modeler 7.1.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the XLSReport module
	public static void aCr_Constraint(IContext context, xlsreport.proxies.MxConstraint _mxConstraint)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxConstraint", _mxConstraint == null ? null : _mxConstraint.getMendixObject());
			Core.execute(context, "XLSReport.ACr_Constraint", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCr_Sorting(IContext context, xlsreport.proxies.MxSorting _mxSorting)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxSorting", _mxSorting == null ? null : _mxSorting.getMendixObject());
			Core.execute(context, "XLSReport.ACr_Sorting", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean bCo_MxData(IContext context, xlsreport.proxies.MxData _mxData)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxData", _mxData == null ? null : _mxData.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "XLSReport.BCo_MxData", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean bCo_Sheet(IContext context, xlsreport.proxies.MxSheet _mxSheet)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxSheet", _mxSheet == null ? null : _mxSheet.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "XLSReport.BCo_Sheet", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean bDe_MxXpath(IContext context, xlsreport.proxies.MxXPath _mxXPath)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxXPath", _mxXPath == null ? null : _mxXPath.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "XLSReport.BDe_MxXpath", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void column_CSV_New(IContext context, xlsreport.proxies.MxSheet _mxSheet)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxSheet", _mxSheet == null ? null : _mxSheet.getMendixObject());
			Core.execute(context, "XLSReport.Column_CSV_New", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.MxObjectMember> dS_Attribute(IContext context, xlsreport.proxies.MxXPath _mxXPath)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxXPath", _mxXPath == null ? null : _mxXPath.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "XLSReport.DS_Attribute", params);
			java.util.List<mxmodelreflection.proxies.MxObjectMember> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectMember>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.MxObjectMember.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.MxObjectMember> dS_Constraint_attribute(IContext context, xlsreport.proxies.MxXPath _mxXpath)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxXpath", _mxXpath == null ? null : _mxXpath.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "XLSReport.DS_Constraint_attribute", params);
			java.util.List<mxmodelreflection.proxies.MxObjectMember> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectMember>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.MxObjectMember.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.MxObjectReference> dS_Constraint_reference(IContext context, xlsreport.proxies.MxXPath _mxXpath)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxXpath", _mxXpath == null ? null : _mxXpath.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "XLSReport.DS_Constraint_reference", params);
			java.util.List<mxmodelreflection.proxies.MxObjectReference> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectReference>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.MxObjectReference.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.MxObjectMember> dS_First_Attribute(IContext context, xlsreport.proxies.MxXPath _mxXpath)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxXpath", _mxXpath == null ? null : _mxXpath.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "XLSReport.DS_First_Attribute", params);
			java.util.List<mxmodelreflection.proxies.MxObjectMember> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectMember>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.MxObjectMember.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.MxObjectReference> dS_First_Reference(IContext context, xlsreport.proxies.MxXPath _mxXpath)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxXpath", _mxXpath == null ? null : _mxXpath.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "XLSReport.DS_First_Reference", params);
			java.util.List<mxmodelreflection.proxies.MxObjectReference> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectReference>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.MxObjectReference.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.MxObjectReference> dS_Reference(IContext context, xlsreport.proxies.MxXPath _mxXPath)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxXPath", _mxXPath == null ? null : _mxXPath.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "XLSReport.DS_Reference", params);
			java.util.List<mxmodelreflection.proxies.MxObjectReference> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectReference>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.MxObjectReference.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.MxObjectMember> dS_Sorting_attribute(IContext context, xlsreport.proxies.MxXPath _mxXpath)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxXpath", _mxXpath == null ? null : _mxXpath.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "XLSReport.DS_Sorting_attribute", params);
			java.util.List<mxmodelreflection.proxies.MxObjectMember> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectMember>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.MxObjectMember.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.MxObjectReference> dS_Sorting_reference(IContext context, xlsreport.proxies.MxXPath _mxXpath)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxXpath", _mxXpath == null ? null : _mxXpath.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "XLSReport.DS_Sorting_reference", params);
			java.util.List<mxmodelreflection.proxies.MxObjectReference> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectReference>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.MxObjectReference.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.MxObjectMember> dS_StaticInputMember(IContext context, xlsreport.proxies.MxStatic _mxStatic)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxStatic", _mxStatic == null ? null : _mxStatic.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "XLSReport.DS_StaticInputMember", params);
			java.util.List<mxmodelreflection.proxies.MxObjectMember> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectMember>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.MxObjectMember.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static xlsreport.proxies.MxSheet dS_TemplateCSVSheet(IContext context, xlsreport.proxies.MxTemplate _mxTemplate)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxTemplate", _mxTemplate == null ? null : _mxTemplate.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "XLSReport.DS_TemplateCSVSheet", params);
			return result == null ? null : xlsreport.proxies.MxSheet.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void generateReport(IContext context, xlsreport.proxies.MxTemplate _template)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Template", _template == null ? null : _template.getMendixObject());
			Core.execute(context, "XLSReport.GenerateReport", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Column_New(IContext context, xlsreport.proxies.MxSheet _mxSheet)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxSheet", _mxSheet == null ? null : _mxSheet.getMendixObject());
			Core.execute(context, "XLSReport.IVK_Column_New", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Column_Save(IContext context, xlsreport.proxies.MxColumn _mxColumn)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxColumn", _mxColumn == null ? null : _mxColumn.getMendixObject());
			Core.execute(context, "XLSReport.IVK_Column_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ColumnHigher(IContext context, xlsreport.proxies.MxColumn _mxColumn)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxColumn", _mxColumn == null ? null : _mxColumn.getMendixObject());
			Core.execute(context, "XLSReport.IVK_ColumnHigher", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ColumnLower(IContext context, xlsreport.proxies.MxColumn _mxColumn)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxColumn", _mxColumn == null ? null : _mxColumn.getMendixObject());
			Core.execute(context, "XLSReport.IVK_ColumnLower", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Constraint_Higher(IContext context, xlsreport.proxies.MxConstraint _mxConstraint, xlsreport.proxies.MxSheet _mxSheet)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxConstraint", _mxConstraint == null ? null : _mxConstraint.getMendixObject());
			params.put("MxSheet", _mxSheet == null ? null : _mxSheet.getMendixObject());
			Core.execute(context, "XLSReport.IVK_Constraint_Higher", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Constraint_Lower(IContext context, xlsreport.proxies.MxConstraint _mxConstraint, xlsreport.proxies.MxSheet _mxSheet)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxConstraint", _mxConstraint == null ? null : _mxConstraint.getMendixObject());
			params.put("MxSheet", _mxSheet == null ? null : _mxSheet.getMendixObject());
			Core.execute(context, "XLSReport.IVK_Constraint_Lower", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ConstraintDelete(IContext context, xlsreport.proxies.MxConstraint _mxConstraint)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxConstraint", _mxConstraint == null ? null : _mxConstraint.getMendixObject());
			Core.execute(context, "XLSReport.IVK_ConstraintDelete", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ConstraintSave(IContext context, xlsreport.proxies.MxConstraint _mxConstraint)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxConstraint", _mxConstraint == null ? null : _mxConstraint.getMendixObject());
			Core.execute(context, "XLSReport.IVK_ConstraintSave", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ConstraintSaveAndNext(IContext context, xlsreport.proxies.MxConstraint _mxConstraint)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxConstraint", _mxConstraint == null ? null : _mxConstraint.getMendixObject());
			Core.execute(context, "XLSReport.IVK_ConstraintSaveAndNext", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_CreateNewSheet(IContext context, xlsreport.proxies.MxTemplate _mxTemplate)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxTemplate", _mxTemplate == null ? null : _mxTemplate.getMendixObject());
			Core.execute(context, "XLSReport.IVK_CreateNewSheet", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_DeleteColumn(IContext context, xlsreport.proxies.MxColumn _mxColumn)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxColumn", _mxColumn == null ? null : _mxColumn.getMendixObject());
			Core.execute(context, "XLSReport.IVK_DeleteColumn", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_DeleteExcistFile(IContext context, xlsreport.proxies.MxTemplate _mxTemplate)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxTemplate", _mxTemplate == null ? null : _mxTemplate.getMendixObject());
			Core.execute(context, "XLSReport.IVK_DeleteExcistFile", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ExcistFile_Save(IContext context, xlsreport.proxies.CustomExcel _excistExcel)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ExcistExcel", _excistExcel == null ? null : _excistExcel.getMendixObject());
			Core.execute(context, "XLSReport.IVK_ExcistFile_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Sorting_Higher(IContext context, xlsreport.proxies.MxSorting _mxSorting, xlsreport.proxies.MxSheet _mxSheet)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxSorting", _mxSorting == null ? null : _mxSorting.getMendixObject());
			params.put("MxSheet", _mxSheet == null ? null : _mxSheet.getMendixObject());
			Core.execute(context, "XLSReport.IVK_Sorting_Higher", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Sorting_Lower(IContext context, xlsreport.proxies.MxSorting _mxSorting, xlsreport.proxies.MxSheet _mxSheet)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxSorting", _mxSorting == null ? null : _mxSorting.getMendixObject());
			params.put("MxSheet", _mxSheet == null ? null : _mxSheet.getMendixObject());
			Core.execute(context, "XLSReport.IVK_Sorting_Lower", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SortingDelete(IContext context, xlsreport.proxies.MxSorting _mxSorting)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxSorting", _mxSorting == null ? null : _mxSorting.getMendixObject());
			Core.execute(context, "XLSReport.IVK_SortingDelete", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SortingSave(IContext context, xlsreport.proxies.MxSorting _mxSorting)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxSorting", _mxSorting == null ? null : _mxSorting.getMendixObject());
			Core.execute(context, "XLSReport.IVK_SortingSave", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_TemplateEdit(IContext context, xlsreport.proxies.MxTemplate _mxTemplate)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxTemplate", _mxTemplate == null ? null : _mxTemplate.getMendixObject());
			Core.execute(context, "XLSReport.IVK_TemplateEdit", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_TemplateSaveAndNext(IContext context, xlsreport.proxies.MxTemplate _template)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Template", _template == null ? null : _template.getMendixObject());
			Core.execute(context, "XLSReport.IVK_TemplateSaveAndNext", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_UploadExcistFile(IContext context, xlsreport.proxies.MxTemplate _mxTemplate)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxTemplate", _mxTemplate == null ? null : _mxTemplate.getMendixObject());
			Core.execute(context, "XLSReport.IVK_UploadExcistFile", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_Sheet_Object(IContext context, xlsreport.proxies.MxSheet _mxSheet)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxSheet", _mxSheet == null ? null : _mxSheet.getMendixObject());
			Core.execute(context, "XLSReport.OCh_Sheet_Object", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_Sheet_Reference(IContext context, xlsreport.proxies.MxSheet _mxSheet)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxSheet", _mxSheet == null ? null : _mxSheet.getMendixObject());
			Core.execute(context, "XLSReport.OCh_Sheet_Reference", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_Template_Save(IContext context, xlsreport.proxies.MxTemplate _mxTemplate)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxTemplate", _mxTemplate == null ? null : _mxTemplate.getMendixObject());
			Core.execute(context, "XLSReport.OCh_Template_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_XPath_Refresh(IContext context, xlsreport.proxies.MxXPath _mxXPath)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxXPath", _mxXPath == null ? null : _mxXPath.getMendixObject());
			Core.execute(context, "XLSReport.OCh_XPath_Refresh", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_Xpath_RetrieveType(IContext context, xlsreport.proxies.MxXPath _parentMxXPath)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ParentMxXPath", _parentMxXPath == null ? null : _parentMxXPath.getMendixObject());
			Core.execute(context, "XLSReport.OCh_Xpath_RetrieveType", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void settings_Save(IContext context, xlsreport.proxies.MxColumnSettings _mxColumnSettings)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxColumnSettings", _mxColumnSettings == null ? null : _mxColumnSettings.getMendixObject());
			Core.execute(context, "XLSReport.Settings_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sF_Column_Validate(IContext context, xlsreport.proxies.MxColumn _mxColumn, boolean _showMessage, xlsreport.proxies.MxSheet _mxSheet)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxColumn", _mxColumn == null ? null : _mxColumn.getMendixObject());
			params.put("ShowMessage", _showMessage);
			params.put("MxSheet", _mxSheet == null ? null : _mxSheet.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "XLSReport.SF_Column_Validate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxmodelreflection.proxies.MxObjectMember sF_FindAttribute(IContext context, xlsreport.proxies.MxXPath _mxXPath)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxXPath", _mxXPath == null ? null : _mxXPath.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "XLSReport.SF_FindAttribute", params);
			return result == null ? null : mxmodelreflection.proxies.MxObjectMember.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static xlsreport.proxies.AttributeType sF_ParseDateType(IContext context, java.lang.String _dateTypeText)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DateTypeText", _dateTypeText);
			java.lang.String result = (java.lang.String)Core.execute(context, "XLSReport.SF_ParseDateType", params);
			if (result == null)
				return null;
			return xlsreport.proxies.AttributeType.valueOf(result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sF_Static_Validate(IContext context, xlsreport.proxies.MxStatic _mxStatic, boolean _showMessage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxStatic", _mxStatic == null ? null : _mxStatic.getMendixObject());
			params.put("ShowMessage", _showMessage);
			return (java.lang.Boolean)Core.execute(context, "XLSReport.SF_Static_Validate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sheet_Save(IContext context, xlsreport.proxies.MxSheet _mxSheet)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxSheet", _mxSheet == null ? null : _mxSheet.getMendixObject());
			Core.execute(context, "XLSReport.Sheet_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void static_New(IContext context, xlsreport.proxies.MxSheet _mxSheet)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxSheet", _mxSheet == null ? null : _mxSheet.getMendixObject());
			Core.execute(context, "XLSReport.Static_New", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean static_Save(IContext context, xlsreport.proxies.MxStatic _mxStatic)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxStatic", _mxStatic == null ? null : _mxStatic.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "XLSReport.Static_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void xPath_Delete_Subs(IContext context, xlsreport.proxies.MxXPath _parentXPath)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ParentXPath", _parentXPath == null ? null : _parentXPath.getMendixObject());
			Core.execute(context, "XLSReport.XPath_Delete_Subs", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void xPath_New(IContext context, xlsreport.proxies.MxData _mxData)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxData", _mxData == null ? null : _mxData.getMendixObject());
			Core.execute(context, "XLSReport.XPath_New", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean xPath_Validate(IContext context, xlsreport.proxies.MxXPath _mxXPath, boolean _showMessage, java.util.List<xlsreport.proxies.MxReferenceHandling> _referenceHandlerList, xlsreport.proxies.MxSheet _mxSheet)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxXPath", _mxXPath == null ? null : _mxXPath.getMendixObject());
			params.put("ShowMessage", _showMessage);
			java.util.ArrayList<IMendixObject> listparam_referenceHandlerList = null;
			if (_referenceHandlerList != null)
			{
				listparam_referenceHandlerList = new java.util.ArrayList<IMendixObject>();
				for (xlsreport.proxies.MxReferenceHandling obj : _referenceHandlerList)
					listparam_referenceHandlerList.add(obj.getMendixObject());
			}
			params.put("ReferenceHandlerList", listparam_referenceHandlerList);
			params.put("MxSheet", _mxSheet == null ? null : _mxSheet.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "XLSReport.XPath_Validate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}