// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

public enum AggregateFunction
{
	Sum(new java.lang.String[][] { new java.lang.String[] { "en_US", "Sum" }, new java.lang.String[] { "nl_NL", "Optellen" } }),
	Max(new java.lang.String[][] { new java.lang.String[] { "en_US", "Max" }, new java.lang.String[] { "nl_NL", "Max" } }),
	Min(new java.lang.String[][] { new java.lang.String[] { "en_US", "Min" }, new java.lang.String[] { "nl_NL", "Min" } }),
	Count(new java.lang.String[][] { new java.lang.String[] { "en_US", "Count" }, new java.lang.String[] { "nl_NL", "Aantal" } }),
	Average(new java.lang.String[][] { new java.lang.String[] { "en_US", "Average" }, new java.lang.String[] { "nl_NL", "Gemiddelde" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private AggregateFunction(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
