// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

public enum AggregateFunction
{
	Sum(new String[][] { new String[] { "en_US", "Sum" }, new String[] { "nl_NL", "Optellen" } }),
	Max(new String[][] { new String[] { "en_US", "Max" }, new String[] { "nl_NL", "Max" } }),
	Min(new String[][] { new String[] { "en_US", "Min" }, new String[] { "nl_NL", "Min" } }),
	Count(new String[][] { new String[] { "en_US", "Count" }, new String[] { "nl_NL", "Aantal" } }),
	Average(new String[][] { new String[] { "en_US", "Average" }, new String[] { "nl_NL", "Gemiddelde" } });

	private java.util.Map<String,String> captions;

	private AggregateFunction(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
