// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

public enum AttributeType
{
	Text(new String[][] { new String[] { "en_US", "String" }, new String[] { "nl_NL", "String" } }),
	Number(new String[][] { new String[] { "en_US", "Integer" }, new String[] { "nl_NL", "Integer" } }),
	Decimal(new String[][] { new String[] { "en_US", "Float" }, new String[] { "nl_NL", "Float" } }),
	Date(new String[][] { new String[] { "en_US", "Date" }, new String[] { "nl_NL", "Datum" } }),
	YesNo(new String[][] { new String[] { "en_US", "Boolean" }, new String[] { "nl_NL", "Boolean" } });

	private java.util.Map<String,String> captions;

	private AttributeType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
