// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

public enum DateTimePresentation
{
	mdyy(new String[][] { new String[] { "en_US", "m/d/yy" } }),
	dmmmyy(new String[][] { new String[] { "en_US", "d-mmm-yy" } }),
	mdyyhmm(new String[][] { new String[] { "en_US", "m/d/yy h:mm" } }),
	ddmmyyyy(new String[][] { new String[] { "en_US", "dd-mm-yyyy" } }),
	ddmmyyyyhhmm(new String[][] { new String[] { "en_US", "dd-mm-yyyy hh:mm" } }),
	mmddyyyy(new String[][] { new String[] { "en_US", "mm/dd/yyyy" } }),
	mmddyyyyhhmm(new String[][] { new String[] { "en_US", "mm/dd/yyyy hh:mm" } }),
	custom(new String[][] { new String[] { "en_US", "custom format" } });

	private java.util.Map<String,String> captions;

	private DateTimePresentation(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
