// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

public enum DocumentType
{
	XLS(new String[][] { new String[] { "en_US", "Excel 97 - 2003" }, new String[] { "nl_NL", "Excel 97 - 2003 werkmap" } }),
	XLSX(new String[][] { new String[] { "en_US", "Excel 2007 and higher" }, new String[] { "nl_NL", "Excel 2007 werkmap (niet ondersteund)" } }),
	CSV(new String[][] { new String[] { "en_US", "CSV file" }, new String[] { "nl_NL", "CSV bestand (niet ondersteund)" } });

	private java.util.Map<String,String> captions;

	private DocumentType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
