// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

public enum JOINType
{
	LEFT(new java.lang.String[][] { new java.lang.String[] { "en_US", "LEFT JOIN" }, new java.lang.String[] { "nl_NL", "LEFT JOIN" } }),
	INNER(new java.lang.String[][] { new java.lang.String[] { "en_US", "INNER JOIN" }, new java.lang.String[] { "nl_NL", "INNER JOIN" } }),
	RIGHT(new java.lang.String[][] { new java.lang.String[] { "en_US", "RIGHT JOIN" }, new java.lang.String[] { "nl_NL", "RIGHT JOIN" } }),
	FULL(new java.lang.String[][] { new java.lang.String[] { "en_US", "FULL JOIN" }, new java.lang.String[] { "nl_NL", "FULL JOIN" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private JOINType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
