// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

/**
 * 
 */
public class MxColumn extends xlsreport.proxies.MxData
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "XLSReport.MxColumn";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ColumnNumber("ColumnNumber"),
		NameAsHeader("NameAsHeader"),
		ObjectAttribute("ObjectAttribute"),
		DataAggregate("DataAggregate"),
		DataAggregateFunction("DataAggregateFunction"),
		ResultAggregate("ResultAggregate"),
		ResultAggregateFunction("ResultAggregateFunction"),
		Name("Name"),
		Status("Status"),
		MxData_MxSheet("XLSReport.MxData_MxSheet"),
		MxData_MxCellStyle("XLSReport.MxData_MxCellStyle"),
		MxXPath_MxData("XLSReport.MxXPath_MxData");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MxColumn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "XLSReport.MxColumn"));
	}

	protected MxColumn(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mxColumnMendixObject)
	{
		super(context, mxColumnMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("XLSReport.MxColumn", mxColumnMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a XLSReport.MxColumn");
	}

	/**
	 * @deprecated Use 'MxColumn.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static xlsreport.proxies.MxColumn initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return xlsreport.proxies.MxColumn.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static xlsreport.proxies.MxColumn initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new xlsreport.proxies.MxColumn(context, mendixObject);
	}

	public static xlsreport.proxies.MxColumn load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return xlsreport.proxies.MxColumn.initialize(context, mendixObject);
	}

	public static java.util.List<xlsreport.proxies.MxColumn> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<xlsreport.proxies.MxColumn> result = new java.util.ArrayList<xlsreport.proxies.MxColumn>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//XLSReport.MxColumn" + xpathConstraint))
			result.add(xlsreport.proxies.MxColumn.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of ColumnNumber
	 */
	public final Integer getColumnNumber()
	{
		return getColumnNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of ColumnNumber
	 */
	public final Integer getColumnNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.ColumnNumber.toString());
	}

	/**
	 * Set value of ColumnNumber
	 * @param columnnumber
	 */
	public final void setColumnNumber(Integer columnnumber)
	{
		setColumnNumber(getContext(), columnnumber);
	}

	/**
	 * Set value of ColumnNumber
	 * @param context
	 * @param columnnumber
	 */
	public final void setColumnNumber(com.mendix.systemwideinterfaces.core.IContext context, Integer columnnumber)
	{
		getMendixObject().setValue(context, MemberNames.ColumnNumber.toString(), columnnumber);
	}

	/**
	 * @return value of NameAsHeader
	 */
	public final Boolean getNameAsHeader()
	{
		return getNameAsHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of NameAsHeader
	 */
	public final Boolean getNameAsHeader(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.NameAsHeader.toString());
	}

	/**
	 * Set value of NameAsHeader
	 * @param nameasheader
	 */
	public final void setNameAsHeader(Boolean nameasheader)
	{
		setNameAsHeader(getContext(), nameasheader);
	}

	/**
	 * Set value of NameAsHeader
	 * @param context
	 * @param nameasheader
	 */
	public final void setNameAsHeader(com.mendix.systemwideinterfaces.core.IContext context, Boolean nameasheader)
	{
		getMendixObject().setValue(context, MemberNames.NameAsHeader.toString(), nameasheader);
	}

	/**
	 * @return value of ObjectAttribute
	 */
	public final String getObjectAttribute()
	{
		return getObjectAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of ObjectAttribute
	 */
	public final String getObjectAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ObjectAttribute.toString());
	}

	/**
	 * Set value of ObjectAttribute
	 * @param objectattribute
	 */
	public final void setObjectAttribute(String objectattribute)
	{
		setObjectAttribute(getContext(), objectattribute);
	}

	/**
	 * Set value of ObjectAttribute
	 * @param context
	 * @param objectattribute
	 */
	public final void setObjectAttribute(com.mendix.systemwideinterfaces.core.IContext context, String objectattribute)
	{
		getMendixObject().setValue(context, MemberNames.ObjectAttribute.toString(), objectattribute);
	}

	/**
	 * @return value of DataAggregate
	 */
	public final Boolean getDataAggregate()
	{
		return getDataAggregate(getContext());
	}

	/**
	 * @param context
	 * @return value of DataAggregate
	 */
	public final Boolean getDataAggregate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.DataAggregate.toString());
	}

	/**
	 * Set value of DataAggregate
	 * @param dataaggregate
	 */
	public final void setDataAggregate(Boolean dataaggregate)
	{
		setDataAggregate(getContext(), dataaggregate);
	}

	/**
	 * Set value of DataAggregate
	 * @param context
	 * @param dataaggregate
	 */
	public final void setDataAggregate(com.mendix.systemwideinterfaces.core.IContext context, Boolean dataaggregate)
	{
		getMendixObject().setValue(context, MemberNames.DataAggregate.toString(), dataaggregate);
	}

	/**
	 * Set value of DataAggregateFunction
	 * @param dataaggregatefunction
	 */
	public final xlsreport.proxies.AggregateFunction getDataAggregateFunction()
	{
		return getDataAggregateFunction(getContext());
	}

	/**
	 * @param context
	 * @return value of DataAggregateFunction
	 */
	public final xlsreport.proxies.AggregateFunction getDataAggregateFunction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DataAggregateFunction.toString());
		if (obj == null)
			return null;

		return xlsreport.proxies.AggregateFunction.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DataAggregateFunction
	 * @param dataaggregatefunction
	 */
	public final void setDataAggregateFunction(xlsreport.proxies.AggregateFunction dataaggregatefunction)
	{
		setDataAggregateFunction(getContext(), dataaggregatefunction);
	}

	/**
	 * Set value of DataAggregateFunction
	 * @param context
	 * @param dataaggregatefunction
	 */
	public final void setDataAggregateFunction(com.mendix.systemwideinterfaces.core.IContext context, xlsreport.proxies.AggregateFunction dataaggregatefunction)
	{
		if (dataaggregatefunction != null)
			getMendixObject().setValue(context, MemberNames.DataAggregateFunction.toString(), dataaggregatefunction.toString());
		else
			getMendixObject().setValue(context, MemberNames.DataAggregateFunction.toString(), null);
	}

	/**
	 * @return value of ResultAggregate
	 */
	public final Boolean getResultAggregate()
	{
		return getResultAggregate(getContext());
	}

	/**
	 * @param context
	 * @return value of ResultAggregate
	 */
	public final Boolean getResultAggregate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.ResultAggregate.toString());
	}

	/**
	 * Set value of ResultAggregate
	 * @param resultaggregate
	 */
	public final void setResultAggregate(Boolean resultaggregate)
	{
		setResultAggregate(getContext(), resultaggregate);
	}

	/**
	 * Set value of ResultAggregate
	 * @param context
	 * @param resultaggregate
	 */
	public final void setResultAggregate(com.mendix.systemwideinterfaces.core.IContext context, Boolean resultaggregate)
	{
		getMendixObject().setValue(context, MemberNames.ResultAggregate.toString(), resultaggregate);
	}

	/**
	 * Set value of ResultAggregateFunction
	 * @param resultaggregatefunction
	 */
	public final xlsreport.proxies.AggregateFunction getResultAggregateFunction()
	{
		return getResultAggregateFunction(getContext());
	}

	/**
	 * @param context
	 * @return value of ResultAggregateFunction
	 */
	public final xlsreport.proxies.AggregateFunction getResultAggregateFunction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ResultAggregateFunction.toString());
		if (obj == null)
			return null;

		return xlsreport.proxies.AggregateFunction.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ResultAggregateFunction
	 * @param resultaggregatefunction
	 */
	public final void setResultAggregateFunction(xlsreport.proxies.AggregateFunction resultaggregatefunction)
	{
		setResultAggregateFunction(getContext(), resultaggregatefunction);
	}

	/**
	 * Set value of ResultAggregateFunction
	 * @param context
	 * @param resultaggregatefunction
	 */
	public final void setResultAggregateFunction(com.mendix.systemwideinterfaces.core.IContext context, xlsreport.proxies.AggregateFunction resultaggregatefunction)
	{
		if (resultaggregatefunction != null)
			getMendixObject().setValue(context, MemberNames.ResultAggregateFunction.toString(), resultaggregatefunction.toString());
		else
			getMendixObject().setValue(context, MemberNames.ResultAggregateFunction.toString(), null);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final xlsreport.proxies.MxColumn that = (xlsreport.proxies.MxColumn) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "XLSReport.MxColumn";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
