// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

public enum MxColor
{
	Blank(new String[][] { new String[] { "en_US", "None" }, new String[] { "nl_NL", "Geen" } }),
	Black(new String[][] { new String[] { "en_US", "Black" }, new String[] { "nl_NL", "Zwart" } }),
	White(new String[][] { new String[] { "en_US", "White" }, new String[] { "nl_NL", "Wit" } }),
	Pink(new String[][] { new String[] { "en_US", "Pink" }, new String[] { "nl_NL", "Rose" } }),
	Red(new String[][] { new String[] { "en_US", "Red" }, new String[] { "nl_NL", "Rood" } }),
	Orange(new String[][] { new String[] { "en_US", "Orange" }, new String[] { "nl_NL", "Oranje" } }),
	Yellow(new String[][] { new String[] { "en_US", "Yellow" }, new String[] { "nl_NL", "Geel" } }),
	Green(new String[][] { new String[] { "en_US", "Green" }, new String[] { "nl_NL", "Groen" } }),
	Light_Blue(new String[][] { new String[] { "en_US", "Light Blue" }, new String[] { "nl_NL", "Licht blauw" } }),
	Blue(new String[][] { new String[] { "en_US", "Blue" }, new String[] { "nl_NL", "Blauw" } }),
	Brown(new String[][] { new String[] { "en_US", "Brown" }, new String[] { "nl_NL", "Bruin" } }),
	Gray_1(new String[][] { new String[] { "en_US", "Gray 25%" }, new String[] { "nl_NL", "Grijs 25%" } }),
	Gray_2(new String[][] { new String[] { "en_US", "Gray 40%" }, new String[] { "nl_NL", "Grijs 40%" } }),
	Gray_3(new String[][] { new String[] { "en_US", "Gray 50%" }, new String[] { "nl_NL", "Grijs 50%" } }),
	Gray_4(new String[][] { new String[] { "en_US", "Gray 80%" }, new String[] { "nl_NL", "Grijs 80%" } });

	private java.util.Map<String,String> captions;

	private MxColor(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
