// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

public enum MxColor
{
	Blank(new java.lang.String[][] { new java.lang.String[] { "en_US", "None" } }),
	Black(new java.lang.String[][] { new java.lang.String[] { "en_US", "Black" } }),
	White(new java.lang.String[][] { new java.lang.String[] { "en_US", "White" } }),
	Pink(new java.lang.String[][] { new java.lang.String[] { "en_US", "Pink" } }),
	Red(new java.lang.String[][] { new java.lang.String[] { "en_US", "Red" } }),
	Orange(new java.lang.String[][] { new java.lang.String[] { "en_US", "Orange" } }),
	Yellow(new java.lang.String[][] { new java.lang.String[] { "en_US", "Yellow" } }),
	Green(new java.lang.String[][] { new java.lang.String[] { "en_US", "Green" } }),
	Light_Blue(new java.lang.String[][] { new java.lang.String[] { "en_US", "Light Blue" } }),
	Blue(new java.lang.String[][] { new java.lang.String[] { "en_US", "Blue" } }),
	Brown(new java.lang.String[][] { new java.lang.String[] { "en_US", "Brown" } }),
	Gray_1(new java.lang.String[][] { new java.lang.String[] { "en_US", "Gray 25%" } }),
	Gray_2(new java.lang.String[][] { new java.lang.String[] { "en_US", "Gray 40%" } }),
	Gray_3(new java.lang.String[][] { new java.lang.String[] { "en_US", "Gray 50%" } }),
	Gray_4(new java.lang.String[][] { new java.lang.String[] { "en_US", "Gray 80%" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private MxColor(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
