// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

public class MxData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mxDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "XLSReport.MxData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Status("Status"),
		MxData_MxSheet("XLSReport.MxData_MxSheet"),
		MxData_MxCellStyle("XLSReport.MxData_MxCellStyle"),
		MxXPath_MxData("XLSReport.MxXPath_MxData");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MxData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "XLSReport.MxData"));
	}

	protected MxData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mxDataMendixObject)
	{
		if (mxDataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("XLSReport.MxData", mxDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a XLSReport.MxData");

		this.mxDataMendixObject = mxDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MxData.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static xlsreport.proxies.MxData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return xlsreport.proxies.MxData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static xlsreport.proxies.MxData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("XLSReport.MxColumn", mendixObject.getType()))
			return xlsreport.proxies.MxColumn.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("XLSReport.MxStatic", mendixObject.getType()))
			return xlsreport.proxies.MxStatic.initialize(context, mendixObject);

		return new xlsreport.proxies.MxData(context, mendixObject);
	}

	public static xlsreport.proxies.MxData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return xlsreport.proxies.MxData.initialize(context, mendixObject);
	}

	public static java.util.List<? extends xlsreport.proxies.MxData> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<xlsreport.proxies.MxData> result = new java.util.ArrayList<xlsreport.proxies.MxData>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//XLSReport.MxData" + xpathConstraint))
			result.add(xlsreport.proxies.MxData.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final xlsreport.proxies.Yes_no getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final xlsreport.proxies.Yes_no getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return xlsreport.proxies.Yes_no.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(xlsreport.proxies.Yes_no status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, xlsreport.proxies.Yes_no status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of MxData_MxSheet
	 */
	public final xlsreport.proxies.MxSheet getMxData_MxSheet() throws com.mendix.core.CoreException
	{
		return getMxData_MxSheet(getContext());
	}

	/**
	 * @param context
	 * @return value of MxData_MxSheet
	 */
	public final xlsreport.proxies.MxSheet getMxData_MxSheet(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		xlsreport.proxies.MxSheet result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxData_MxSheet.toString());
		if (identifier != null)
			result = xlsreport.proxies.MxSheet.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxData_MxSheet
	 * @param mxdata_mxsheet
	 */
	public final void setMxData_MxSheet(xlsreport.proxies.MxSheet mxdata_mxsheet)
	{
		setMxData_MxSheet(getContext(), mxdata_mxsheet);
	}

	/**
	 * Set value of MxData_MxSheet
	 * @param context
	 * @param mxdata_mxsheet
	 */
	public final void setMxData_MxSheet(com.mendix.systemwideinterfaces.core.IContext context, xlsreport.proxies.MxSheet mxdata_mxsheet)
	{
		if (mxdata_mxsheet == null)
			getMendixObject().setValue(context, MemberNames.MxData_MxSheet.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxData_MxSheet.toString(), mxdata_mxsheet.getMendixObject().getId());
	}

	/**
	 * @return value of MxData_MxCellStyle
	 */
	public final xlsreport.proxies.MxCellStyle getMxData_MxCellStyle() throws com.mendix.core.CoreException
	{
		return getMxData_MxCellStyle(getContext());
	}

	/**
	 * @param context
	 * @return value of MxData_MxCellStyle
	 */
	public final xlsreport.proxies.MxCellStyle getMxData_MxCellStyle(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		xlsreport.proxies.MxCellStyle result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxData_MxCellStyle.toString());
		if (identifier != null)
			result = xlsreport.proxies.MxCellStyle.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxData_MxCellStyle
	 * @param mxdata_mxcellstyle
	 */
	public final void setMxData_MxCellStyle(xlsreport.proxies.MxCellStyle mxdata_mxcellstyle)
	{
		setMxData_MxCellStyle(getContext(), mxdata_mxcellstyle);
	}

	/**
	 * Set value of MxData_MxCellStyle
	 * @param context
	 * @param mxdata_mxcellstyle
	 */
	public final void setMxData_MxCellStyle(com.mendix.systemwideinterfaces.core.IContext context, xlsreport.proxies.MxCellStyle mxdata_mxcellstyle)
	{
		if (mxdata_mxcellstyle == null)
			getMendixObject().setValue(context, MemberNames.MxData_MxCellStyle.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxData_MxCellStyle.toString(), mxdata_mxcellstyle.getMendixObject().getId());
	}

	/**
	 * @return value of MxXPath_MxData
	 */
	public final xlsreport.proxies.MxXPath getMxXPath_MxData() throws com.mendix.core.CoreException
	{
		return getMxXPath_MxData(getContext());
	}

	/**
	 * @param context
	 * @return value of MxXPath_MxData
	 */
	public final xlsreport.proxies.MxXPath getMxXPath_MxData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		xlsreport.proxies.MxXPath result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxXPath_MxData.toString());
		if (identifier != null)
			result = xlsreport.proxies.MxXPath.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxXPath_MxData
	 * @param mxxpath_mxdata
	 */
	public final void setMxXPath_MxData(xlsreport.proxies.MxXPath mxxpath_mxdata)
	{
		setMxXPath_MxData(getContext(), mxxpath_mxdata);
	}

	/**
	 * Set value of MxXPath_MxData
	 * @param context
	 * @param mxxpath_mxdata
	 */
	public final void setMxXPath_MxData(com.mendix.systemwideinterfaces.core.IContext context, xlsreport.proxies.MxXPath mxxpath_mxdata)
	{
		if (mxxpath_mxdata == null)
			getMendixObject().setValue(context, MemberNames.MxXPath_MxData.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxXPath_MxData.toString(), mxxpath_mxdata.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mxDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final xlsreport.proxies.MxData that = (xlsreport.proxies.MxData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "XLSReport.MxData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
