// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

/**
 * 
 */
public class MxRowSettings
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mxRowSettingsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "XLSReport.MxRowSettings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RowIndex("RowIndex"),
		DefaultHeight("DefaultHeight"),
		RowHeight("RowHeight"),
		MxRowSettings_MxSheet("XLSReport.MxRowSettings_MxSheet");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MxRowSettings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "XLSReport.MxRowSettings"));
	}

	protected MxRowSettings(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mxRowSettingsMendixObject)
	{
		if (mxRowSettingsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("XLSReport.MxRowSettings", mxRowSettingsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a XLSReport.MxRowSettings");

		this.mxRowSettingsMendixObject = mxRowSettingsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MxRowSettings.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static xlsreport.proxies.MxRowSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return xlsreport.proxies.MxRowSettings.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static xlsreport.proxies.MxRowSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new xlsreport.proxies.MxRowSettings(context, mendixObject);
	}

	public static xlsreport.proxies.MxRowSettings load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return xlsreport.proxies.MxRowSettings.initialize(context, mendixObject);
	}

	public static java.util.List<xlsreport.proxies.MxRowSettings> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<xlsreport.proxies.MxRowSettings> result = new java.util.ArrayList<xlsreport.proxies.MxRowSettings>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//XLSReport.MxRowSettings" + xpathConstraint))
			result.add(xlsreport.proxies.MxRowSettings.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of RowIndex
	 */
	public final Integer getRowIndex()
	{
		return getRowIndex(getContext());
	}

	/**
	 * @param context
	 * @return value of RowIndex
	 */
	public final Integer getRowIndex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.RowIndex.toString());
	}

	/**
	 * Set value of RowIndex
	 * @param rowindex
	 */
	public final void setRowIndex(Integer rowindex)
	{
		setRowIndex(getContext(), rowindex);
	}

	/**
	 * Set value of RowIndex
	 * @param context
	 * @param rowindex
	 */
	public final void setRowIndex(com.mendix.systemwideinterfaces.core.IContext context, Integer rowindex)
	{
		getMendixObject().setValue(context, MemberNames.RowIndex.toString(), rowindex);
	}

	/**
	 * @return value of DefaultHeight
	 */
	public final Boolean getDefaultHeight()
	{
		return getDefaultHeight(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultHeight
	 */
	public final Boolean getDefaultHeight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.DefaultHeight.toString());
	}

	/**
	 * Set value of DefaultHeight
	 * @param defaultheight
	 */
	public final void setDefaultHeight(Boolean defaultheight)
	{
		setDefaultHeight(getContext(), defaultheight);
	}

	/**
	 * Set value of DefaultHeight
	 * @param context
	 * @param defaultheight
	 */
	public final void setDefaultHeight(com.mendix.systemwideinterfaces.core.IContext context, Boolean defaultheight)
	{
		getMendixObject().setValue(context, MemberNames.DefaultHeight.toString(), defaultheight);
	}

	/**
	 * @return value of RowHeight
	 */
	public final Integer getRowHeight()
	{
		return getRowHeight(getContext());
	}

	/**
	 * @param context
	 * @return value of RowHeight
	 */
	public final Integer getRowHeight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.RowHeight.toString());
	}

	/**
	 * Set value of RowHeight
	 * @param rowheight
	 */
	public final void setRowHeight(Integer rowheight)
	{
		setRowHeight(getContext(), rowheight);
	}

	/**
	 * Set value of RowHeight
	 * @param context
	 * @param rowheight
	 */
	public final void setRowHeight(com.mendix.systemwideinterfaces.core.IContext context, Integer rowheight)
	{
		getMendixObject().setValue(context, MemberNames.RowHeight.toString(), rowheight);
	}

	/**
	 * @return value of MxRowSettings_MxSheet
	 */
	public final xlsreport.proxies.MxSheet getMxRowSettings_MxSheet() throws com.mendix.core.CoreException
	{
		return getMxRowSettings_MxSheet(getContext());
	}

	/**
	 * @param context
	 * @return value of MxRowSettings_MxSheet
	 */
	public final xlsreport.proxies.MxSheet getMxRowSettings_MxSheet(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		xlsreport.proxies.MxSheet result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxRowSettings_MxSheet.toString());
		if (identifier != null)
			result = xlsreport.proxies.MxSheet.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxRowSettings_MxSheet
	 * @param mxrowsettings_mxsheet
	 */
	public final void setMxRowSettings_MxSheet(xlsreport.proxies.MxSheet mxrowsettings_mxsheet)
	{
		setMxRowSettings_MxSheet(getContext(), mxrowsettings_mxsheet);
	}

	/**
	 * Set value of MxRowSettings_MxSheet
	 * @param context
	 * @param mxrowsettings_mxsheet
	 */
	public final void setMxRowSettings_MxSheet(com.mendix.systemwideinterfaces.core.IContext context, xlsreport.proxies.MxSheet mxrowsettings_mxsheet)
	{
		if (mxrowsettings_mxsheet == null)
			getMendixObject().setValue(context, MemberNames.MxRowSettings_MxSheet.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxRowSettings_MxSheet.toString(), mxrowsettings_mxsheet.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mxRowSettingsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final xlsreport.proxies.MxRowSettings that = (xlsreport.proxies.MxRowSettings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "XLSReport.MxRowSettings";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
