// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

public class MxXPath
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mxXPathMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "XLSReport.MxXPath";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RetrieveType("RetrieveType"),
		SubVisible("SubVisible"),
		ChildMxXPath_MxXPath("XLSReport.ChildMxXPath_MxXPath"),
		MxXPath_MxData("XLSReport.MxXPath_MxData"),
		MxXPath_ParentMxXPath("XLSReport.MxXPath_ParentMxXPath"),
		MxConstraint_MxXPath("XLSReport.MxConstraint_MxXPath"),
		MxSorting_MxXPath("XLSReport.MxSorting_MxXPath"),
		MxXPath_MxObjectMember("XLSReport.MxXPath_MxObjectMember"),
		MxXPath_MxObjectReference("XLSReport.MxXPath_MxObjectReference"),
		MxXPath_MxObjectType("XLSReport.MxXPath_MxObjectType");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MxXPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "XLSReport.MxXPath"));
	}

	protected MxXPath(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mxXPathMendixObject)
	{
		if (mxXPathMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("XLSReport.MxXPath", mxXPathMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a XLSReport.MxXPath");

		this.mxXPathMendixObject = mxXPathMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MxXPath.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static xlsreport.proxies.MxXPath initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return xlsreport.proxies.MxXPath.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static xlsreport.proxies.MxXPath initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new xlsreport.proxies.MxXPath(context, mendixObject);
	}

	public static xlsreport.proxies.MxXPath load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return xlsreport.proxies.MxXPath.initialize(context, mendixObject);
	}

	public static java.util.List<xlsreport.proxies.MxXPath> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<xlsreport.proxies.MxXPath> result = new java.util.ArrayList<xlsreport.proxies.MxXPath>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//XLSReport.MxXPath" + xpathConstraint))
			result.add(xlsreport.proxies.MxXPath.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of RetrieveType
	 * @param retrievetype
	 */
	public final xlsreport.proxies.RetrieveAction getRetrieveType()
	{
		return getRetrieveType(getContext());
	}

	/**
	 * @param context
	 * @return value of RetrieveType
	 */
	public final xlsreport.proxies.RetrieveAction getRetrieveType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RetrieveType.toString());
		if (obj == null)
			return null;

		return xlsreport.proxies.RetrieveAction.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RetrieveType
	 * @param retrievetype
	 */
	public final void setRetrieveType(xlsreport.proxies.RetrieveAction retrievetype)
	{
		setRetrieveType(getContext(), retrievetype);
	}

	/**
	 * Set value of RetrieveType
	 * @param context
	 * @param retrievetype
	 */
	public final void setRetrieveType(com.mendix.systemwideinterfaces.core.IContext context, xlsreport.proxies.RetrieveAction retrievetype)
	{
		if (retrievetype != null)
			getMendixObject().setValue(context, MemberNames.RetrieveType.toString(), retrievetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.RetrieveType.toString(), null);
	}

	/**
	 * @return value of SubVisible
	 */
	public final java.lang.Boolean getSubVisible()
	{
		return getSubVisible(getContext());
	}

	/**
	 * @param context
	 * @return value of SubVisible
	 */
	public final java.lang.Boolean getSubVisible(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SubVisible.toString());
	}

	/**
	 * Set value of SubVisible
	 * @param subvisible
	 */
	public final void setSubVisible(java.lang.Boolean subvisible)
	{
		setSubVisible(getContext(), subvisible);
	}

	/**
	 * Set value of SubVisible
	 * @param context
	 * @param subvisible
	 */
	public final void setSubVisible(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean subvisible)
	{
		getMendixObject().setValue(context, MemberNames.SubVisible.toString(), subvisible);
	}

	/**
	 * @return value of ChildMxXPath_MxXPath
	 */
	public final xlsreport.proxies.MxXPath getChildMxXPath_MxXPath() throws com.mendix.core.CoreException
	{
		return getChildMxXPath_MxXPath(getContext());
	}

	/**
	 * @param context
	 * @return value of ChildMxXPath_MxXPath
	 */
	public final xlsreport.proxies.MxXPath getChildMxXPath_MxXPath(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		xlsreport.proxies.MxXPath result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ChildMxXPath_MxXPath.toString());
		if (identifier != null)
			result = xlsreport.proxies.MxXPath.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ChildMxXPath_MxXPath
	 * @param childmxxpath_mxxpath
	 */
	public final void setChildMxXPath_MxXPath(xlsreport.proxies.MxXPath childmxxpath_mxxpath)
	{
		setChildMxXPath_MxXPath(getContext(), childmxxpath_mxxpath);
	}

	/**
	 * Set value of ChildMxXPath_MxXPath
	 * @param context
	 * @param childmxxpath_mxxpath
	 */
	public final void setChildMxXPath_MxXPath(com.mendix.systemwideinterfaces.core.IContext context, xlsreport.proxies.MxXPath childmxxpath_mxxpath)
	{
		if (childmxxpath_mxxpath == null)
			getMendixObject().setValue(context, MemberNames.ChildMxXPath_MxXPath.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ChildMxXPath_MxXPath.toString(), childmxxpath_mxxpath.getMendixObject().getId());
	}

	/**
	 * @return value of MxXPath_MxData
	 */
	public final xlsreport.proxies.MxData getMxXPath_MxData() throws com.mendix.core.CoreException
	{
		return getMxXPath_MxData(getContext());
	}

	/**
	 * @param context
	 * @return value of MxXPath_MxData
	 */
	public final xlsreport.proxies.MxData getMxXPath_MxData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		xlsreport.proxies.MxData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxXPath_MxData.toString());
		if (identifier != null)
			result = xlsreport.proxies.MxData.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxXPath_MxData
	 * @param mxxpath_mxdata
	 */
	public final void setMxXPath_MxData(xlsreport.proxies.MxData mxxpath_mxdata)
	{
		setMxXPath_MxData(getContext(), mxxpath_mxdata);
	}

	/**
	 * Set value of MxXPath_MxData
	 * @param context
	 * @param mxxpath_mxdata
	 */
	public final void setMxXPath_MxData(com.mendix.systemwideinterfaces.core.IContext context, xlsreport.proxies.MxData mxxpath_mxdata)
	{
		if (mxxpath_mxdata == null)
			getMendixObject().setValue(context, MemberNames.MxXPath_MxData.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxXPath_MxData.toString(), mxxpath_mxdata.getMendixObject().getId());
	}

	/**
	 * @return value of MxXPath_ParentMxXPath
	 */
	public final xlsreport.proxies.MxXPath getMxXPath_ParentMxXPath() throws com.mendix.core.CoreException
	{
		return getMxXPath_ParentMxXPath(getContext());
	}

	/**
	 * @param context
	 * @return value of MxXPath_ParentMxXPath
	 */
	public final xlsreport.proxies.MxXPath getMxXPath_ParentMxXPath(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		xlsreport.proxies.MxXPath result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxXPath_ParentMxXPath.toString());
		if (identifier != null)
			result = xlsreport.proxies.MxXPath.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxXPath_ParentMxXPath
	 * @param mxxpath_parentmxxpath
	 */
	public final void setMxXPath_ParentMxXPath(xlsreport.proxies.MxXPath mxxpath_parentmxxpath)
	{
		setMxXPath_ParentMxXPath(getContext(), mxxpath_parentmxxpath);
	}

	/**
	 * Set value of MxXPath_ParentMxXPath
	 * @param context
	 * @param mxxpath_parentmxxpath
	 */
	public final void setMxXPath_ParentMxXPath(com.mendix.systemwideinterfaces.core.IContext context, xlsreport.proxies.MxXPath mxxpath_parentmxxpath)
	{
		if (mxxpath_parentmxxpath == null)
			getMendixObject().setValue(context, MemberNames.MxXPath_ParentMxXPath.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxXPath_ParentMxXPath.toString(), mxxpath_parentmxxpath.getMendixObject().getId());
	}

	/**
	 * @return value of MxConstraint_MxXPath
	 */
	public final xlsreport.proxies.MxConstraint getMxConstraint_MxXPath() throws com.mendix.core.CoreException
	{
		return getMxConstraint_MxXPath(getContext());
	}

	/**
	 * @param context
	 * @return value of MxConstraint_MxXPath
	 */
	public final xlsreport.proxies.MxConstraint getMxConstraint_MxXPath(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		xlsreport.proxies.MxConstraint result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxConstraint_MxXPath.toString());
		if (identifier != null)
			result = xlsreport.proxies.MxConstraint.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxConstraint_MxXPath
	 * @param mxconstraint_mxxpath
	 */
	public final void setMxConstraint_MxXPath(xlsreport.proxies.MxConstraint mxconstraint_mxxpath)
	{
		setMxConstraint_MxXPath(getContext(), mxconstraint_mxxpath);
	}

	/**
	 * Set value of MxConstraint_MxXPath
	 * @param context
	 * @param mxconstraint_mxxpath
	 */
	public final void setMxConstraint_MxXPath(com.mendix.systemwideinterfaces.core.IContext context, xlsreport.proxies.MxConstraint mxconstraint_mxxpath)
	{
		if (mxconstraint_mxxpath == null)
			getMendixObject().setValue(context, MemberNames.MxConstraint_MxXPath.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxConstraint_MxXPath.toString(), mxconstraint_mxxpath.getMendixObject().getId());
	}

	/**
	 * @return value of MxSorting_MxXPath
	 */
	public final xlsreport.proxies.MxSorting getMxSorting_MxXPath() throws com.mendix.core.CoreException
	{
		return getMxSorting_MxXPath(getContext());
	}

	/**
	 * @param context
	 * @return value of MxSorting_MxXPath
	 */
	public final xlsreport.proxies.MxSorting getMxSorting_MxXPath(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		xlsreport.proxies.MxSorting result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxSorting_MxXPath.toString());
		if (identifier != null)
			result = xlsreport.proxies.MxSorting.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxSorting_MxXPath
	 * @param mxsorting_mxxpath
	 */
	public final void setMxSorting_MxXPath(xlsreport.proxies.MxSorting mxsorting_mxxpath)
	{
		setMxSorting_MxXPath(getContext(), mxsorting_mxxpath);
	}

	/**
	 * Set value of MxSorting_MxXPath
	 * @param context
	 * @param mxsorting_mxxpath
	 */
	public final void setMxSorting_MxXPath(com.mendix.systemwideinterfaces.core.IContext context, xlsreport.proxies.MxSorting mxsorting_mxxpath)
	{
		if (mxsorting_mxxpath == null)
			getMendixObject().setValue(context, MemberNames.MxSorting_MxXPath.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxSorting_MxXPath.toString(), mxsorting_mxxpath.getMendixObject().getId());
	}

	/**
	 * @return value of MxXPath_MxObjectMember
	 */
	public final mxmodelreflection.proxies.MxObjectMember getMxXPath_MxObjectMember() throws com.mendix.core.CoreException
	{
		return getMxXPath_MxObjectMember(getContext());
	}

	/**
	 * @param context
	 * @return value of MxXPath_MxObjectMember
	 */
	public final mxmodelreflection.proxies.MxObjectMember getMxXPath_MxObjectMember(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectMember result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxXPath_MxObjectMember.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectMember.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxXPath_MxObjectMember
	 * @param mxxpath_mxobjectmember
	 */
	public final void setMxXPath_MxObjectMember(mxmodelreflection.proxies.MxObjectMember mxxpath_mxobjectmember)
	{
		setMxXPath_MxObjectMember(getContext(), mxxpath_mxobjectmember);
	}

	/**
	 * Set value of MxXPath_MxObjectMember
	 * @param context
	 * @param mxxpath_mxobjectmember
	 */
	public final void setMxXPath_MxObjectMember(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectMember mxxpath_mxobjectmember)
	{
		if (mxxpath_mxobjectmember == null)
			getMendixObject().setValue(context, MemberNames.MxXPath_MxObjectMember.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxXPath_MxObjectMember.toString(), mxxpath_mxobjectmember.getMendixObject().getId());
	}

	/**
	 * @return value of MxXPath_MxObjectReference
	 */
	public final mxmodelreflection.proxies.MxObjectReference getMxXPath_MxObjectReference() throws com.mendix.core.CoreException
	{
		return getMxXPath_MxObjectReference(getContext());
	}

	/**
	 * @param context
	 * @return value of MxXPath_MxObjectReference
	 */
	public final mxmodelreflection.proxies.MxObjectReference getMxXPath_MxObjectReference(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectReference result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxXPath_MxObjectReference.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectReference.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxXPath_MxObjectReference
	 * @param mxxpath_mxobjectreference
	 */
	public final void setMxXPath_MxObjectReference(mxmodelreflection.proxies.MxObjectReference mxxpath_mxobjectreference)
	{
		setMxXPath_MxObjectReference(getContext(), mxxpath_mxobjectreference);
	}

	/**
	 * Set value of MxXPath_MxObjectReference
	 * @param context
	 * @param mxxpath_mxobjectreference
	 */
	public final void setMxXPath_MxObjectReference(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectReference mxxpath_mxobjectreference)
	{
		if (mxxpath_mxobjectreference == null)
			getMendixObject().setValue(context, MemberNames.MxXPath_MxObjectReference.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxXPath_MxObjectReference.toString(), mxxpath_mxobjectreference.getMendixObject().getId());
	}

	/**
	 * @return value of MxXPath_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getMxXPath_MxObjectType() throws com.mendix.core.CoreException
	{
		return getMxXPath_MxObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of MxXPath_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getMxXPath_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxXPath_MxObjectType.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxXPath_MxObjectType
	 * @param mxxpath_mxobjecttype
	 */
	public final void setMxXPath_MxObjectType(mxmodelreflection.proxies.MxObjectType mxxpath_mxobjecttype)
	{
		setMxXPath_MxObjectType(getContext(), mxxpath_mxobjecttype);
	}

	/**
	 * Set value of MxXPath_MxObjectType
	 * @param context
	 * @param mxxpath_mxobjecttype
	 */
	public final void setMxXPath_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectType mxxpath_mxobjecttype)
	{
		if (mxxpath_mxobjecttype == null)
			getMendixObject().setValue(context, MemberNames.MxXPath_MxObjectType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxXPath_MxObjectType.toString(), mxxpath_mxobjecttype.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mxXPathMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final xlsreport.proxies.MxXPath that = (xlsreport.proxies.MxXPath) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "XLSReport.MxXPath";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
