// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

public enum TextAlignment
{
	Left(new String[][] { new String[] { "en_US", "Left" }, new String[] { "nl_NL", "Links" } }),
	Center(new String[][] { new String[] { "en_US", "Center" }, new String[] { "nl_NL", "Gecentreerd" } }),
	Right(new String[][] { new String[] { "en_US", "Right" }, new String[] { "nl_NL", "Rechts" } });

	private java.util.Map<String,String> captions;

	private TextAlignment(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
