// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

public enum TextVerticalAlignment
{
	Top(new java.lang.String[][] { new java.lang.String[] { "en_US", "Top" }, new java.lang.String[] { "nl_NL", "Boven" } }),
	Middle(new java.lang.String[][] { new java.lang.String[] { "en_US", "Middle" }, new java.lang.String[] { "nl_NL", "Midden" } }),
	Bottom(new java.lang.String[][] { new java.lang.String[] { "en_US", "Bottom" }, new java.lang.String[] { "nl_NL", "Onder" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private TextVerticalAlignment(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
