// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

public enum TextVerticalAlignment
{
	Top(new String[][] { new String[] { "en_US", "Top" }, new String[] { "nl_NL", "Boven" } }),
	Middle(new String[][] { new String[] { "en_US", "Middle" }, new String[] { "nl_NL", "Midden" } }),
	Bottom(new String[][] { new String[] { "en_US", "Bottom" }, new String[] { "nl_NL", "Onder" } });

	private java.util.Map<String,String> captions;

	private TextVerticalAlignment(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
