// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxmodelreflection.proxies;

public enum AssociationOwner
{
	_Default(new String[][] { new String[] { "nl_NL", "Default" }, new String[] { "en_GB", "Default" }, new String[] { "en_US", "Default" }, new String[] { "en_ZA", "Default" } }),
	Both(new String[][] { new String[] { "nl_NL", "Beide" }, new String[] { "en_GB", "Both" }, new String[] { "en_US", "Both" }, new String[] { "en_ZA", "Both" } });

	private java.util.Map<String,String> captions;

	private AssociationOwner(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
