// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxmodelreflection.proxies;

public enum PrimitiveTypes
{
	AutoNumber(new String[][] { new String[] { "en_US", "Auto number" }, new String[] { "nl_NL", "Autonummer" }, new String[] { "en_GB", "Auto number" }, new String[] { "en_ZA", "Auto number" } }),
	BooleanType(new String[][] { new String[] { "en_US", "Boolean" }, new String[] { "nl_NL", "Boolean" }, new String[] { "en_GB", "Boolean" }, new String[] { "en_ZA", "Boolean" } }),
	Currency(new String[][] { new String[] { "en_US", "Currency" }, new String[] { "nl_NL", "Currency" }, new String[] { "en_GB", "Currency" }, new String[] { "en_ZA", "Currency" } }),
	DateTime(new String[][] { new String[] { "en_US", "DateTime" }, new String[] { "nl_NL", "DateTime" }, new String[] { "en_GB", "DateTime" }, new String[] { "en_ZA", "DateTime" } }),
	EnumType(new String[][] { new String[] { "en_US", "Enum" }, new String[] { "nl_NL", "Enum" }, new String[] { "en_GB", "Enum" }, new String[] { "en_ZA", "Enum" } }),
	FloatType(new String[][] { new String[] { "en_US", "Float" }, new String[] { "nl_NL", "Float" }, new String[] { "en_GB", "Float" }, new String[] { "en_ZA", "Float" } }),
	HashString(new String[][] { new String[] { "en_US", "Hash string (i.e. passwords)" }, new String[] { "nl_NL", "Hash string (bv. wachtwoorden)" }, new String[] { "en_GB", "Hash string (i.e. passwords)" }, new String[] { "en_ZA", "Hash string (i.e. passwords)" } }),
	IntegerType(new String[][] { new String[] { "en_US", "Integer" }, new String[] { "nl_NL", "Integer" }, new String[] { "en_GB", "Integer" }, new String[] { "en_ZA", "Integer" } }),
	LongType(new String[][] { new String[] { "en_US", "Long" }, new String[] { "nl_NL", "Long" }, new String[] { "en_GB", "Long" }, new String[] { "en_ZA", "Long" } }),
	StringType(new String[][] { new String[] { "en_US", "String" }, new String[] { "nl_NL", "String" }, new String[] { "en_GB", "String" }, new String[] { "en_ZA", "String" } }),
	ObjectType(new String[][] { new String[] { "en_US", "Object Type" }, new String[] { "en_GB", "Object Type" }, new String[] { "en_ZA", "Object Type" }, new String[] { "nl_NL", "Object Type" } }),
	ObjectList(new String[][] { new String[] { "en_US", "Object List" }, new String[] { "en_GB", "Object List" }, new String[] { "en_ZA", "Object List" }, new String[] { "nl_NL", "Object Lijst" } }),
	Decimal(new String[][] { new String[] { "en_US", "Decimal" }, new String[] { "nl_NL", "Decimal" }, new String[] { "en_GB", "Decimal" }, new String[] { "en_ZA", "Decimal" } });

	private java.util.Map<String,String> captions;

	private PrimitiveTypes(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
