// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxmodelreflection.proxies;

public enum ReferenceType
{
	Reference(new String[][] { new String[] { "en_US", "Reference" }, new String[] { "nl_NL", "Referentie" }, new String[] { "en_GB", "Reference" }, new String[] { "en_ZA", "Reference" } }),
	ReferenceSet(new String[][] { new String[] { "en_US", "Reference set" }, new String[] { "nl_NL", "Reference set" }, new String[] { "en_GB", "Reference set" }, new String[] { "en_ZA", "Reference set" } });

	private java.util.Map<String,String> captions;

	private ReferenceType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
