// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package odm.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the ODM module
	public static void iVK_AsyncNew(IContext context, odm.proxies.Order _order)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Order", _order == null ? null : _order.getMendixObject());
		Core.microflowCall("ODM.IVK_AsyncNew").withParams(params).execute(context);
	}
	public static void iVK_DeleteAll(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ODM.IVK_DeleteAll").withParams(params).execute(context);
	}
	public static void iVK_GenerateData(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ODM.IVK_GenerateData").withParams(params).execute(context);
	}
	public static void iVK_GenerateReport(IContext context, xlsreport.proxies.MxTemplate _mxTemplate, odm.proxies.Order _order)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MxTemplate", _mxTemplate == null ? null : _mxTemplate.getMendixObject());
		params.put("Order", _order == null ? null : _order.getMendixObject());
		Core.microflowCall("ODM.IVK_GenerateReport").withParams(params).execute(context);
	}
	public static void iVK_SaveOrderLine(IContext context, odm.proxies.OrderLine _orderLine)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OrderLine", _orderLine == null ? null : _orderLine.getMendixObject());
		Core.microflowCall("ODM.IVK_SaveOrderLine").withParams(params).execute(context);
	}
	public static void oCh_OrderLine(IContext context, odm.proxies.OrderLine _orderLine)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OrderLine", _orderLine == null ? null : _orderLine.getMendixObject());
		Core.microflowCall("ODM.OCh_OrderLine").withParams(params).execute(context);
	}
	public static java.lang.String vA_ProductName(IContext context, odm.proxies.Product _product)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Product", _product == null ? null : _product.getMendixObject());
		return (java.lang.String) Core.microflowCall("ODM.VA_ProductName").withParams(params).execute(context);
	}
}