// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum ImportActions
{
	SynchronizeObjects(new java.lang.String[][] { new java.lang.String[] { "en_US", "Synchronize objects" }, new java.lang.String[] { "nl_NL", "Synchroniseer objecten" }, new java.lang.String[] { "en_GB", "Synchronize objects" }, new java.lang.String[] { "en_ZA", "Synchronize objects" } }),
	SynchronizeOnlyExisting(new java.lang.String[][] { new java.lang.String[] { "en_US", "Synchronize only existing objects, ignore others" }, new java.lang.String[] { "nl_NL", "Synchroniseer alleen bestaande objecten, negeer de rest" }, new java.lang.String[] { "en_GB", "Synchronize only existing objects, ignore others" }, new java.lang.String[] { "en_ZA", "Synchronize only existing objects, ignore others" } }),
	CreateObjects(new java.lang.String[][] { new java.lang.String[] { "en_US", "Create an object for each row" }, new java.lang.String[] { "nl_NL", "Creeër een object voor iedere rij" }, new java.lang.String[] { "en_GB", "Create an object for each row" }, new java.lang.String[] { "en_ZA", "Create an object for each row" } }),
	OnlyCreateNewObjects(new java.lang.String[][] { new java.lang.String[] { "en_US", "Only create not existing object" }, new java.lang.String[] { "nl_NL", "Creeër alleen niet bestaande objecten" }, new java.lang.String[] { "en_GB", "Only create not existing object" }, new java.lang.String[] { "en_ZA", "Only create not existing object" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private ImportActions(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
