// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public class Log
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject logMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ExcelImporter.Log";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Logline("Logline"),
		Log_XMLDocumentTemplate("ExcelImporter.Log_XMLDocumentTemplate");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Log(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ExcelImporter.Log"));
	}

	protected Log(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject logMendixObject)
	{
		if (logMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ExcelImporter.Log", logMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ExcelImporter.Log");

		this.logMendixObject = logMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Log.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static excelimporter.proxies.Log initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return excelimporter.proxies.Log.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static excelimporter.proxies.Log initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excelimporter.proxies.Log(context, mendixObject);
	}

	public static excelimporter.proxies.Log load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excelimporter.proxies.Log.initialize(context, mendixObject);
	}

	public static java.util.List<excelimporter.proxies.Log> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<excelimporter.proxies.Log> result = new java.util.ArrayList<excelimporter.proxies.Log>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ExcelImporter.Log" + xpathConstraint))
			result.add(excelimporter.proxies.Log.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Logline
	 */
	public final java.lang.String getLogline()
	{
		return getLogline(getContext());
	}

	/**
	 * @param context
	 * @return value of Logline
	 */
	public final java.lang.String getLogline(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Logline.toString());
	}

	/**
	 * Set value of Logline
	 * @param logline
	 */
	public final void setLogline(java.lang.String logline)
	{
		setLogline(getContext(), logline);
	}

	/**
	 * Set value of Logline
	 * @param context
	 * @param logline
	 */
	public final void setLogline(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String logline)
	{
		getMendixObject().setValue(context, MemberNames.Logline.toString(), logline);
	}

	/**
	 * @return value of Log_XMLDocumentTemplate
	 */
	public final excelimporter.proxies.XMLDocumentTemplate getLog_XMLDocumentTemplate() throws com.mendix.core.CoreException
	{
		return getLog_XMLDocumentTemplate(getContext());
	}

	/**
	 * @param context
	 * @return value of Log_XMLDocumentTemplate
	 */
	public final excelimporter.proxies.XMLDocumentTemplate getLog_XMLDocumentTemplate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excelimporter.proxies.XMLDocumentTemplate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Log_XMLDocumentTemplate.toString());
		if (identifier != null)
			result = excelimporter.proxies.XMLDocumentTemplate.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Log_XMLDocumentTemplate
	 * @param log_xmldocumenttemplate
	 */
	public final void setLog_XMLDocumentTemplate(excelimporter.proxies.XMLDocumentTemplate log_xmldocumenttemplate)
	{
		setLog_XMLDocumentTemplate(getContext(), log_xmldocumenttemplate);
	}

	/**
	 * Set value of Log_XMLDocumentTemplate
	 * @param context
	 * @param log_xmldocumenttemplate
	 */
	public final void setLog_XMLDocumentTemplate(com.mendix.systemwideinterfaces.core.IContext context, excelimporter.proxies.XMLDocumentTemplate log_xmldocumenttemplate)
	{
		if (log_xmldocumenttemplate == null)
			getMendixObject().setValue(context, MemberNames.Log_XMLDocumentTemplate.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Log_XMLDocumentTemplate.toString(), log_xmldocumenttemplate.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return logMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excelimporter.proxies.Log that = (excelimporter.proxies.Log) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ExcelImporter.Log";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
