// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum ReferenceKeyType
{
	NoKey(new String[][] { new String[] { "en_US", "NoKey" }, new String[] { "nl_NL", "Nee" }, new String[] { "en_GB", "NoKey" }, new String[] { "en_ZA", "NoKey" } }),
	YesOnlyAssociatedObject(new String[][] { new String[] { "en_US", "Yes, only for the associated object" }, new String[] { "nl_NL", "Ja, alleen voor het geassocieerde object" }, new String[] { "en_GB", "Yes, only for the associated object" }, new String[] { "en_ZA", "Yes, only for the associated object" } }),
	YesOnlyMainObject(new String[][] { new String[] { "en_US", "Yes, only for the main object" }, new String[] { "nl_NL", "Ja, alleen voor het hoofd object" }, new String[] { "en_GB", "Yes, only for the main object" }, new String[] { "en_ZA", "Yes, only for the main object" } }),
	YesMainAndAssociatedObject(new String[][] { new String[] { "en_US", "Yes, Both for the main object and the associated object" }, new String[] { "nl_NL", "Ja, voor het hoofd object en het geassocieerde object" }, new String[] { "en_GB", "Yes, Both for the main object and the associated object" }, new String[] { "en_ZA", "Yes, Both for the main object and the associated object" } });

	private java.util.Map<String,String> captions;

	private ReferenceKeyType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
