// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum RemoveIndicator
{
	TrackChanges(new String[][] { new String[] { "nl_NL", "Hou alleen de wijzigingen bij" }, new String[] { "en_US", "Track changes" }, new String[] { "en_GB", "Track changes" }, new String[] { "en_ZA", "Track changes" } }),
	RemoveUnchangedObjects(new String[][] { new String[] { "nl_NL", "Verwijder alle ongewijzigde objecten" }, new String[] { "en_US", "Remove unchanged objects" }, new String[] { "en_GB", "Remove unchanged objects" }, new String[] { "en_ZA", "Remove unchanged objects" } }),
	Nothing(new String[][] { new String[] { "nl_NL", "Niets" }, new String[] { "en_US", "Nothing" }, new String[] { "en_GB", "Nothing" }, new String[] { "en_ZA", "Nothing" } });

	private java.util.Map<String,String> captions;

	private RemoveIndicator(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
