// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum Status
{
	INFO(new String[][] { new String[] { "en_US", "INFO" }, new String[] { "nl_NL", "INFO" }, new String[] { "en_GB", "INFO" }, new String[] { "en_ZA", "INFO" } }),
	VALID(new String[][] { new String[] { "en_US", "Valid" }, new String[] { "nl_NL", "Geldig" }, new String[] { "en_GB", "Valid" }, new String[] { "en_ZA", "Valid" } }),
	INVALID(new String[][] { new String[] { "en_US", "INVALID" }, new String[] { "nl_NL", "INVALID" }, new String[] { "en_GB", "INVALID" }, new String[] { "en_ZA", "INVALID" } });

	private java.util.Map<String,String> captions;

	private Status(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
