// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum StatisticsLevel
{
	AllStatistics(new String[][] { new String[] { "en_US", "All Statistics" }, new String[] { "nl_NL", "Alle Statistieken" }, new String[] { "en_GB", "All Statistics" }, new String[] { "en_ZA", "All Statistics" } }),
	OnlyFinalStatistics(new String[][] { new String[] { "en_US", "Only Final Statistics" }, new String[] { "nl_NL", "Alleen volledige statistieken" }, new String[] { "en_GB", "Only Final Statistics" }, new String[] { "en_ZA", "Only Final Statistics" } }),
	NoStatistics(new String[][] { new String[] { "en_US", "No Statistics" }, new String[] { "nl_NL", "Geen Statistieken" }, new String[] { "en_GB", "No Statistics" }, new String[] { "en_ZA", "No Statistics" } });

	private java.util.Map<String,String> captions;

	private StatisticsLevel(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
