// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum TemplateType
{
	Normal(new String[][] { new String[] { "en_US", "Normal" }, new String[] { "nl_NL", "Normaal" }, new String[] { "en_GB", "Normal" }, new String[] { "en_ZA", "Normal" } }),
	Wizard(new String[][] { new String[] { "en_US", "Wizard" }, new String[] { "nl_NL", "Wizard" }, new String[] { "en_GB", "Wizard" }, new String[] { "en_ZA", "Wizard" } });

	private java.util.Map<String,String> captions;

	private TemplateType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
