// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

/**
 * The template is the starting entity for the excel module. This wrapper contains all the settings for the excel import. 
 * Within this template several columns can be added. 
 */
public class Template
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject templateMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ExcelImporter.Template";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Nr("Nr"),
		Title("Title"),
		Description("Description"),
		SheetIndex("SheetIndex"),
		HeaderRowNumber("HeaderRowNumber"),
		FirstDataRowNumber("FirstDataRowNumber"),
		Status("Status"),
		ImportAction("ImportAction"),
		TemplateType("TemplateType"),
		Template_AdditionalProperties("ExcelImporter.Template_AdditionalProperties"),
		Template_MasterTemplate("ExcelImporter.Template_MasterTemplate"),
		Template_MxObjectType("ExcelImporter.Template_MxObjectType"),
		Template_MxObjectReference_ParentAssociation("ExcelImporter.Template_MxObjectReference_ParentAssociation");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Template(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ExcelImporter.Template"));
	}

	protected Template(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject templateMendixObject)
	{
		if (templateMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ExcelImporter.Template", templateMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ExcelImporter.Template");

		this.templateMendixObject = templateMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Template.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static excelimporter.proxies.Template initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return excelimporter.proxies.Template.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static excelimporter.proxies.Template initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excelimporter.proxies.Template(context, mendixObject);
	}

	public static excelimporter.proxies.Template load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excelimporter.proxies.Template.initialize(context, mendixObject);
	}

	public static java.util.List<excelimporter.proxies.Template> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<excelimporter.proxies.Template> result = new java.util.ArrayList<excelimporter.proxies.Template>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ExcelImporter.Template" + xpathConstraint))
			result.add(excelimporter.proxies.Template.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Nr
	 */
	public final java.lang.Long getNr()
	{
		return getNr(getContext());
	}

	/**
	 * @param context
	 * @return value of Nr
	 */
	public final java.lang.Long getNr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Nr.toString());
	}

	/**
	 * Set value of Nr
	 * @param nr
	 */
	public final void setNr(java.lang.Long nr)
	{
		setNr(getContext(), nr);
	}

	/**
	 * Set value of Nr
	 * @param context
	 * @param nr
	 */
	public final void setNr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long nr)
	{
		getMendixObject().setValue(context, MemberNames.Nr.toString(), nr);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of SheetIndex
	 */
	public final java.lang.Integer getSheetIndex()
	{
		return getSheetIndex(getContext());
	}

	/**
	 * @param context
	 * @return value of SheetIndex
	 */
	public final java.lang.Integer getSheetIndex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SheetIndex.toString());
	}

	/**
	 * Set value of SheetIndex
	 * @param sheetindex
	 */
	public final void setSheetIndex(java.lang.Integer sheetindex)
	{
		setSheetIndex(getContext(), sheetindex);
	}

	/**
	 * Set value of SheetIndex
	 * @param context
	 * @param sheetindex
	 */
	public final void setSheetIndex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sheetindex)
	{
		getMendixObject().setValue(context, MemberNames.SheetIndex.toString(), sheetindex);
	}

	/**
	 * @return value of HeaderRowNumber
	 */
	public final java.lang.Integer getHeaderRowNumber()
	{
		return getHeaderRowNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of HeaderRowNumber
	 */
	public final java.lang.Integer getHeaderRowNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.HeaderRowNumber.toString());
	}

	/**
	 * Set value of HeaderRowNumber
	 * @param headerrownumber
	 */
	public final void setHeaderRowNumber(java.lang.Integer headerrownumber)
	{
		setHeaderRowNumber(getContext(), headerrownumber);
	}

	/**
	 * Set value of HeaderRowNumber
	 * @param context
	 * @param headerrownumber
	 */
	public final void setHeaderRowNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer headerrownumber)
	{
		getMendixObject().setValue(context, MemberNames.HeaderRowNumber.toString(), headerrownumber);
	}

	/**
	 * @return value of FirstDataRowNumber
	 */
	public final java.lang.Integer getFirstDataRowNumber()
	{
		return getFirstDataRowNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstDataRowNumber
	 */
	public final java.lang.Integer getFirstDataRowNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.FirstDataRowNumber.toString());
	}

	/**
	 * Set value of FirstDataRowNumber
	 * @param firstdatarownumber
	 */
	public final void setFirstDataRowNumber(java.lang.Integer firstdatarownumber)
	{
		setFirstDataRowNumber(getContext(), firstdatarownumber);
	}

	/**
	 * Set value of FirstDataRowNumber
	 * @param context
	 * @param firstdatarownumber
	 */
	public final void setFirstDataRowNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer firstdatarownumber)
	{
		getMendixObject().setValue(context, MemberNames.FirstDataRowNumber.toString(), firstdatarownumber);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final excelimporter.proxies.Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final excelimporter.proxies.Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return excelimporter.proxies.Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(excelimporter.proxies.Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, excelimporter.proxies.Status status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * Set value of ImportAction
	 * @param importaction
	 */
	public final excelimporter.proxies.ImportActions getImportAction()
	{
		return getImportAction(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportAction
	 */
	public final excelimporter.proxies.ImportActions getImportAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ImportAction.toString());
		if (obj == null)
			return null;

		return excelimporter.proxies.ImportActions.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ImportAction
	 * @param importaction
	 */
	public final void setImportAction(excelimporter.proxies.ImportActions importaction)
	{
		setImportAction(getContext(), importaction);
	}

	/**
	 * Set value of ImportAction
	 * @param context
	 * @param importaction
	 */
	public final void setImportAction(com.mendix.systemwideinterfaces.core.IContext context, excelimporter.proxies.ImportActions importaction)
	{
		if (importaction != null)
			getMendixObject().setValue(context, MemberNames.ImportAction.toString(), importaction.toString());
		else
			getMendixObject().setValue(context, MemberNames.ImportAction.toString(), null);
	}

	/**
	 * Set value of TemplateType
	 * @param templatetype
	 */
	public final excelimporter.proxies.TemplateType getTemplateType()
	{
		return getTemplateType(getContext());
	}

	/**
	 * @param context
	 * @return value of TemplateType
	 */
	public final excelimporter.proxies.TemplateType getTemplateType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TemplateType.toString());
		if (obj == null)
			return null;

		return excelimporter.proxies.TemplateType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TemplateType
	 * @param templatetype
	 */
	public final void setTemplateType(excelimporter.proxies.TemplateType templatetype)
	{
		setTemplateType(getContext(), templatetype);
	}

	/**
	 * Set value of TemplateType
	 * @param context
	 * @param templatetype
	 */
	public final void setTemplateType(com.mendix.systemwideinterfaces.core.IContext context, excelimporter.proxies.TemplateType templatetype)
	{
		if (templatetype != null)
			getMendixObject().setValue(context, MemberNames.TemplateType.toString(), templatetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.TemplateType.toString(), null);
	}

	/**
	 * @return value of Template_AdditionalProperties
	 */
	public final excelimporter.proxies.AdditionalProperties getTemplate_AdditionalProperties() throws com.mendix.core.CoreException
	{
		return getTemplate_AdditionalProperties(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_AdditionalProperties
	 */
	public final excelimporter.proxies.AdditionalProperties getTemplate_AdditionalProperties(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excelimporter.proxies.AdditionalProperties result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Template_AdditionalProperties.toString());
		if (identifier != null)
			result = excelimporter.proxies.AdditionalProperties.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Template_AdditionalProperties
	 * @param template_additionalproperties
	 */
	public final void setTemplate_AdditionalProperties(excelimporter.proxies.AdditionalProperties template_additionalproperties)
	{
		setTemplate_AdditionalProperties(getContext(), template_additionalproperties);
	}

	/**
	 * Set value of Template_AdditionalProperties
	 * @param context
	 * @param template_additionalproperties
	 */
	public final void setTemplate_AdditionalProperties(com.mendix.systemwideinterfaces.core.IContext context, excelimporter.proxies.AdditionalProperties template_additionalproperties)
	{
		if (template_additionalproperties == null)
			getMendixObject().setValue(context, MemberNames.Template_AdditionalProperties.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Template_AdditionalProperties.toString(), template_additionalproperties.getMendixObject().getId());
	}

	/**
	 * @return value of Template_MasterTemplate
	 */
	public final excelimporter.proxies.Template getTemplate_MasterTemplate() throws com.mendix.core.CoreException
	{
		return getTemplate_MasterTemplate(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_MasterTemplate
	 */
	public final excelimporter.proxies.Template getTemplate_MasterTemplate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excelimporter.proxies.Template result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Template_MasterTemplate.toString());
		if (identifier != null)
			result = excelimporter.proxies.Template.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Template_MasterTemplate
	 * @param template_mastertemplate
	 */
	public final void setTemplate_MasterTemplate(excelimporter.proxies.Template template_mastertemplate)
	{
		setTemplate_MasterTemplate(getContext(), template_mastertemplate);
	}

	/**
	 * Set value of Template_MasterTemplate
	 * @param context
	 * @param template_mastertemplate
	 */
	public final void setTemplate_MasterTemplate(com.mendix.systemwideinterfaces.core.IContext context, excelimporter.proxies.Template template_mastertemplate)
	{
		if (template_mastertemplate == null)
			getMendixObject().setValue(context, MemberNames.Template_MasterTemplate.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Template_MasterTemplate.toString(), template_mastertemplate.getMendixObject().getId());
	}

	/**
	 * @return value of Template_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getTemplate_MxObjectType() throws com.mendix.core.CoreException
	{
		return getTemplate_MxObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getTemplate_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Template_MxObjectType.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Template_MxObjectType
	 * @param template_mxobjecttype
	 */
	public final void setTemplate_MxObjectType(mxmodelreflection.proxies.MxObjectType template_mxobjecttype)
	{
		setTemplate_MxObjectType(getContext(), template_mxobjecttype);
	}

	/**
	 * Set value of Template_MxObjectType
	 * @param context
	 * @param template_mxobjecttype
	 */
	public final void setTemplate_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectType template_mxobjecttype)
	{
		if (template_mxobjecttype == null)
			getMendixObject().setValue(context, MemberNames.Template_MxObjectType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Template_MxObjectType.toString(), template_mxobjecttype.getMendixObject().getId());
	}

	/**
	 * @return value of Template_MxObjectReference_ParentAssociation
	 */
	public final mxmodelreflection.proxies.MxObjectReference getTemplate_MxObjectReference_ParentAssociation() throws com.mendix.core.CoreException
	{
		return getTemplate_MxObjectReference_ParentAssociation(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_MxObjectReference_ParentAssociation
	 */
	public final mxmodelreflection.proxies.MxObjectReference getTemplate_MxObjectReference_ParentAssociation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectReference result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Template_MxObjectReference_ParentAssociation.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectReference.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Template_MxObjectReference_ParentAssociation
	 * @param template_mxobjectreference_parentassociation
	 */
	public final void setTemplate_MxObjectReference_ParentAssociation(mxmodelreflection.proxies.MxObjectReference template_mxobjectreference_parentassociation)
	{
		setTemplate_MxObjectReference_ParentAssociation(getContext(), template_mxobjectreference_parentassociation);
	}

	/**
	 * Set value of Template_MxObjectReference_ParentAssociation
	 * @param context
	 * @param template_mxobjectreference_parentassociation
	 */
	public final void setTemplate_MxObjectReference_ParentAssociation(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectReference template_mxobjectreference_parentassociation)
	{
		if (template_mxobjectreference_parentassociation == null)
			getMendixObject().setValue(context, MemberNames.Template_MxObjectReference_ParentAssociation.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Template_MxObjectReference_ParentAssociation.toString(), template_mxobjectreference_parentassociation.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return templateMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excelimporter.proxies.Template that = (excelimporter.proxies.Template) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ExcelImporter.Template";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
