// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum YesNo
{
	Yes(new java.lang.String[][] { new java.lang.String[] { "en_US", "Yes" }, new java.lang.String[] { "nl_NL", "Ja" }, new java.lang.String[] { "en_GB", "Yes" }, new java.lang.String[] { "en_ZA", "Yes" } }),
	No(new java.lang.String[][] { new java.lang.String[] { "en_US", "No" }, new java.lang.String[] { "nl_NL", "Nee" }, new java.lang.String[] { "en_GB", "No" }, new java.lang.String[] { "en_ZA", "No" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private YesNo(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
