// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum YesNo
{
	Yes(new String[][] { new String[] { "en_US", "Yes" }, new String[] { "nl_NL", "Ja" }, new String[] { "en_GB", "Yes" }, new String[] { "en_ZA", "Yes" } }),
	No(new String[][] { new String[] { "en_US", "No" }, new String[] { "nl_NL", "Nee" }, new String[] { "en_GB", "No" }, new String[] { "en_ZA", "No" } });

	private java.util.Map<String,String> captions;

	private YesNo(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
